'use client';
import { useEffect, useRef, useState } from 'react';
import { GitBranch, Play, Shuffle, Code2, ArrowRight, Download, RotateCcw, ShieldCheck, ExternalLink, AlertCircle, UserRound, FilePlus2, Square } from 'lucide-react';
import { API, request } from '../lib/api';
import type { Candidate, Message, Source, Graph, GraphState, NodeEvent, SavedSession } from '../lib/types';
import Transcript from '../components/Transcript';
import Inspector from '../components/Inspector';
type SessionSummary={id:string;topic:string;status:string;created_at:string};
const disclaimer='This application generates AI simulations based on public sources. Generated responses are not authentic candidate statements.';
export default function Page(){
 const [candidates,setCandidates]=useState<Candidate[]>([]),[sources,setSources]=useState<Source[]>([]),[graph,setGraph]=useState<Graph|null>(null),[topics,setTopics]=useState<string[]>([]),[sessions,setSessions]=useState<SessionSummary[]>([]);
 const [a,setA]=useState('lula'),[b,setB]=useState('flavio'),[topic,setTopic]=useState('Inteligência artificial'),[depth,setDepth]=useState(3),[rounds,setRounds]=useState(1),[first,setFirst]=useState('a'),[responds,setResponds]=useState('b');
 const [dev,setDev]=useState(true),[running,setRunning]=useState(false),[sessionId,setSessionId]=useState(''),[status,setStatus]=useState('Pronto para começar'),[error,setError]=useState(''),[connected,setConnected]=useState(false),[pause,setPause]=useState(false);
 const [messages,setMessages]=useState<Message[]>([]),[current,setCurrent]=useState(''),[state,setState]=useState<GraphState>({}),[events,setEvents]=useState<NodeEvent[]>([]),[importing,setImporting]=useState(false);
 const [sourceUrl,setSourceUrl]=useState(''),[sourceTitle,setSourceTitle]=useState(''),[publisher,setPublisher]=useState('TSE'),[sourceCandidate,setSourceCandidate]=useState('lula'),[sourceType,setSourceType]=useState('government_program'),[sourceDate,setSourceDate]=useState(''),[importStatus,setImportStatus]=useState('');
 const [styleMode,setStyleMode]=useState('expressive');
 const stream=useRef<EventSource|null>(null);
 async function refresh(){const [cs,ss,gs,ts,logs]=await Promise.all([request<Candidate[]>('/api/candidates'),request<Source[]>('/api/sources'),request<Graph>('/api/graph'),request<string[]>('/api/topics'),request<SessionSummary[]>('/api/sessions')]);setCandidates(cs);setSources(ss);setGraph(gs);setTopics(ts);setSessions(logs);setConnected(true);}
 useEffect(()=>{refresh().catch(e=>{setError('Backend indisponível. Inicie o servidor local e clique em reconectar. '+e.message);setConnected(false);});return()=>stream.current?.close();},[]);
 function openStream(id:string,resume=false){
  setRunning(true);setError('');setStatus('Executando');
  const source=new EventSource(`${API}/api/sessions/${id}/stream${resume?'?resume=true':''}`);stream.current=source;
  source.onmessage=(event)=>{
   const data=JSON.parse(event.data);
   if(data.type==='node_start')setCurrent(data.node);
   if(data.type==='graph_update'){setCurrent(data.node);if(data.update&&typeof data.update==='object')setState(s=>({...s,...data.update}));}
   if(data.type==='node_end'){setState(data.state);setEvents(data.state.execution_metadata??[]);}
   if(data.type==='message'||data.type==='message_start')setMessages(ms=>ms.some(m=>m.id===data.message.id)?ms:([...ms,data.message]));
   if(data.type==='token')setMessages(ms=>ms.map(m=>m.id===data.message_id?{...m,content:m.content+data.text}:m));
   if(data.type==='message_end'){setMessages(ms=>ms.map(m=>m.id===data.message.id?data.message:m));request<Source[]>('/api/sources').then(setSources).catch(()=>{});}
   if(data.type==='complete'||data.type==='paused'){source.close();setRunning(false);setStatus(data.type==='complete'?'Concluído':'Pausado');setState(data.state);setEvents(data.state.execution_metadata??[]);setCurrent(data.type==='complete'?'complete':'round_pause');refresh().catch(e=>setError(e.message));}
   if(data.type==='error'){source.close();setRunning(false);setStatus('Erro · sessão recuperável');setError(data.message);}
  };
  source.onerror=()=>{source.close();setRunning(false);setStatus('Interrompido');setError('A conexão foi interrompida. Retome a sessão para continuar do checkpoint.');};
 }
 async function start(){try{setError('');const result=await request<{session_id:string}>('/api/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_a:a,candidate_b:b,topic,asks_first:first,responds_first:responds,depth,max_turns:rounds,mode:'live',pause_after_round:pause,style_mode:styleMode})});setMessages([]);setEvents([]);setState({});setSessionId(result.session_id);openStream(result.session_id);}catch(e){setError((e as Error).message);}}
 function stop(){stream.current?.close();setRunning(false);setStatus('Interrompido');}
 async function restore(id:string){if(!id)return;try{const log=await request<SavedSession>(`/api/sessions/${id}`),checkpoint=await request<{state:GraphState}>(`/api/sessions/${id}/state`);setSessionId(id);setTopic(log.topic);setMessages(log.messages);setEvents(log.execution_metadata);setState(checkpoint.state);setStatus(log.status==='complete'?'Concluído':log.status==='paused'?'Pausado':'Interrompido');setA(log.configuration.candidate_a as string);setB(log.configuration.candidate_b as string);setError('');}catch(e){setError((e as Error).message);}}
 async function download(){try{const log=await request<SavedSession>(`/api/sessions/${sessionId}`);const url=URL.createObjectURL(new Blob([JSON.stringify(log,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`debategraph-${sessionId}.json`;link.click();URL.revokeObjectURL(url);}catch(e){setError((e as Error).message);}}
 async function ingest(){setImporting(true);setImportStatus('Baixando, extraindo e indexando…');try{const result=await request<{unchanged:boolean;chunks:number}>('/api/sources/ingest',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidate_id:sourceCandidate,title:sourceTitle,url:sourceUrl,publisher,source_type:sourceType,publication_date:sourceDate||null,election_year:sourceType==='government_program'?2026:null})});setImportStatus(result.unchanged?'Fonte já importada; nenhum embedding repetido.':`Fonte importada · ${result.chunks} trechos indexados.`);await refresh();}catch(e){setImportStatus('Falha: '+(e as Error).message);}finally{setImporting(false);}}
 const eligible=candidates.filter(c=>!c.fictional),selectedA=candidates.find(c=>c.id===a),selectedB=candidates.find(c=>c.id===b);
 const ready=connected&&a!==b&&topic.trim().length>=2&&!running;
 return <div className="app-shell"><header className="topbar"><a href="/" className="brand" aria-label="DebateGraph início"><span className="brand-icon"><GitBranch size={22}/></span><strong>Debate<span>Graph</span></strong></a><span className="header-divider"/><span className="product-label">Laboratório aberto de IA</span><div className="topbar-right"><span className={connected?'connection connected':'connection'}><i/>{connected?'Backend conectado':'Backend offline'}</span><button className={dev?'dev-button selected':'dev-button'} onClick={()=>setDev(!dev)} aria-pressed={dev}><Code2 size={15}/>Modo desenvolvedor</button><a className="docs-link" href={`${API}/docs`} target="_blank" rel="noreferrer" aria-label="Documentação da API"><ExternalLink size={16}/></a></div></header>
  <div className="integrity-banner"><ShieldCheck size={16}/><p>{disclaimer}</p><span>Sem recomendações de voto</span></div>
  <div className={dev?'workspace':'workspace no-inspector'}><aside className="controls"><div className="control-heading"><h1>Configure o debate</h1><p>Participantes, tema e profundidade.</p></div>
   <p className="configuration-note" style={{marginBottom:20}}>Cinco participantes · fontes públicas verificáveis.</p>
   <div className="field"><label htmlFor="candidate-a">Participante A</label><select id="candidate-a" value={a} onChange={e=>setA(e.target.value)} disabled={running}>{eligible.map(c=><option value={c.id} key={c.id}>{c.short_name} · {c.party}</option>)}</select><div className="candidate-preview"><UserRound size={19}/><span>{selectedA?.name??'Carregando…'}<small>{selectedA?.source_count??0} fontes indexadas</small></span></div></div>
   <div className="field"><label htmlFor="candidate-b">Participante B</label><select id="candidate-b" value={b} onChange={e=>setB(e.target.value)} disabled={running}>{eligible.map(c=><option value={c.id} key={c.id}>{c.short_name} · {c.party}</option>)}</select><div className="candidate-preview"><UserRound size={19}/><span>{selectedB?.name??'Carregando…'}<small>{selectedB?.source_count??0} fontes indexadas</small></span></div></div>
   {a===b&&<p className="field-error">Escolha dois participantes distintos.</p>}
   <div className="field topic-field"><div className="label-row"><label htmlFor="topic">Tema do debate</label><button className="random" aria-label="Sortear tema neutro" disabled={running||!topics.length} onClick={()=>setTopic(topics[Math.floor(Math.random()*topics.length)])}><Shuffle size={12}/>Sortear</button></div><textarea id="topic" value={topic} onChange={e=>setTopic(e.target.value)} maxLength={300} rows={2} disabled={running}/><div className="topic-suggestions">{['Educação','Saúde','Segurança pública'].map(t=><button key={t} onClick={()=>setTopic(t)} disabled={running}>{t}</button>)}</div></div>
   <div className="field"><label htmlFor="depth">Profundidade</label><select id="depth" value={depth} onChange={e=>setDepth(Number(e.target.value))} disabled={running}><option value={1}>Pergunta + resposta</option><option value={2}>Pergunta + resposta + réplica</option><option value={3}>Pergunta + resposta + réplica + tréplica</option></select></div>
   <div className="paired-fields"><div className="field"><label htmlFor="asks">Pergunta primeiro</label><select id="asks" value={first} disabled={running} onChange={e=>{setFirst(e.target.value);setResponds(e.target.value==='a'?'b':'a');}}><option value="a">Participante A</option><option value="b">Participante B</option></select></div><div className="field"><label htmlFor="responds">Responde primeiro</label><select id="responds" value={responds} disabled={running} onChange={e=>{setResponds(e.target.value);setFirst(e.target.value==='a'?'b':'a');}}><option value="a">Participante A</option><option value="b">Participante B</option></select></div></div>
   <div className="field"><label htmlFor="style-mode">Estilo da simulação</label><select id="style-mode" value={styleMode} disabled={running} onChange={e=>setStyleMode(e.target.value)}><option value="expressive">Expressivo · direção de estilo</option><option value="evidence">Somente estilo extraído de fontes</option></select><p className="configuration-note">Vocativos e sarcasmo são recursos da simulação. Propostas exigem evidências.</p></div>
   <div className="field"><label htmlFor="rounds">Rodadas</label><input id="rounds" type="number" min="1" max="5" value={rounds} disabled={running} onChange={e=>setRounds(Number(e.target.value))}/></div>
   <label className="check-field"><input type="checkbox" checked={pause} onChange={e=>setPause(e.target.checked)} disabled={running}/>Pausar a cada rodada para inspeção</label>
   <button className="start-button" onClick={running?stop:start} disabled={!running&&!ready}>{running?<><Square size={15}/>Interromper execução</>:<><Play size={15} fill="currentColor"/>Iniciar debate<ArrowRight size={16}/></>}</button><p className="configuration-note">Somente posições sustentadas por fontes. Fatos são citados; argumentos e provocações mantêm o debate em movimento.</p>
   <details className="import-section"><summary><FilePlus2 size={14}/>Importar uma fonte</summary><div className="import-form"><label htmlFor="source-candidate">Participante</label><select id="source-candidate" value={sourceCandidate} onChange={e=>setSourceCandidate(e.target.value)}>{candidates.filter(c=>!c.fictional).map(c=><option key={c.id} value={c.id}>{c.short_name}</option>)}</select><label htmlFor="source-url">URL pública</label><input id="source-url" type="url" value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://www.tse.jus.br/…"/><label htmlFor="source-title">Título</label><input id="source-title" value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)}/><label htmlFor="publisher">Publicador</label><input id="publisher" value={publisher} onChange={e=>setPublisher(e.target.value)}/><label htmlFor="source-type">Tipo</label><select id="source-type" value={sourceType} onChange={e=>setSourceType(e.target.value)}><option value="government_program">Programa de governo TSE · 2026</option><option value="official_website">Site oficial</option><option value="official_interview">Entrevista oficial</option><option value="official_speech">Discurso oficial</option><option value="debate_transcript">Transcrição de debate</option><option value="journalism">Jornalismo</option></select><label htmlFor="source-date">Data de publicação (se conhecida)</label><input id="source-date" type="date" value={sourceDate} onChange={e=>setSourceDate(e.target.value)}/><button className="secondary" onClick={ingest} disabled={importing||!sourceUrl||!sourceTitle}>{importing?'Importando…':'Importar e indexar'}</button><p role="status">{importStatus}</p></div></details>
  </aside>
  <main className="debate-panel"><div className="debate-heading"><div><div className="live-caption"><span className={running?'pulse-dot':'quiet-dot'}/>SIMULAÇÃO COM FONTES PÚBLICAS</div><h2>{topic||'Seu próximo debate'}</h2></div><div className="transcript-actions"><button disabled={!sessionId||running} onClick={download} aria-label="Exportar log JSON"><Download size={17}/></button>{sessionId&&!running&&status!=='Concluído'&&<button onClick={()=>openStream(sessionId,true)} aria-label="Retomar sessão"><RotateCcw size={17}/></button>}</div></div>
   <div className="session-strip"><span>{status}</span><code>{sessionId?`thread ${sessionId.slice(0,8)}`:'Nenhuma sessão iniciada'}</code><span>{messages.length} mensagens</span></div>
   {error&&<div className="error-banner" role="alert"><AlertCircle size={16}/><p>{error}</p>{!connected&&<button onClick={()=>refresh().then(()=>setError('')).catch(e=>setError(e.message))}>Reconectar</button>}</div>}
   <Transcript messages={messages} candidates={candidates} sources={sources} running={running} current={current}/>
   <footer className="debate-footer"><span><ShieldCheck size={13}/>Conteúdo validado antes da transmissão</span><select aria-label="Abrir sessão salva" onChange={e=>restore(e.target.value)} value="" disabled={running}><option value="">Sessões salvas ({sessions.length})</option>{sessions.map(s=><option key={s.id} value={s.id}>{s.topic} · {s.status} · {s.id.slice(0,6)}</option>)}</select></footer>
  </main>{dev&&<Inspector graph={graph} current={current} state={state} events={events}/>}</div>
  <footer className="app-footer"><span>DebateGraph <span className="muted">/</span> experimento educacional open source</span><span>LangGraph · LangChain · RAG · pgvector</span></footer>
 </div>;
}
